/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionallys, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FacilityRouteImport } from './routes/facility'
import { Route as InstallationRouteImport } from './routes/installation'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ScrewPilesRouteImport } from './routes/screw-piles'
import { Route as ApplicationsIndexRouteImport } from './routes/applications.index'
import { Route as ApplicationsSlugRouteImport } from './routes/applications.$slug'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilityRoute = FacilityRouteImport.update({
  id: '/facility',
  path: '/facility',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallationRoute = InstallationRouteImport.update({
  id: '/installation',
  path: '/installation',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ScrewPilesRoute = ScrewPilesRouteImport.update({
  id: '/screw-piles',
  path: '/screw-piles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsIndexRoute = ApplicationsIndexRouteImport.update({
  id: '/applications/',
  path: '/applications/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsSlugRoute = ApplicationsSlugRouteImport.update({
  id: '/applications/$slug',
  path: '/applications/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/facility': typeof FacilityRoute
  '/installation': typeof InstallationRoute
  '/projects': typeof ProjectsRoute
  '/screw-piles': typeof ScrewPilesRoute
  '/applications/$slug': typeof ApplicationsSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/applications/': typeof ApplicationsIndexRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/facility': typeof FacilityRoute
  '/installation': typeof InstallationRoute
  '/projects': typeof ProjectsRoute
  '/screw-piles': typeof ScrewPilesRoute
  '/applications/$slug': typeof ApplicationsSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/applications': typeof ApplicationsIndexRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/facility': typeof FacilityRoute
  '/installation': typeof InstallationRoute
  '/projects': typeof ProjectsRoute
  '/screw-piles': typeof ScrewPilesRoute
  '/applications/$slug': typeof ApplicationsSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/applications/': typeof ApplicationsIndexRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/facility'
    | '/installation'
    | '/projects'
    | '/screw-piles'
    | '/applications/$slug'
    | '/blog/$slug'
    | '/applications/'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/facility'
    | '/installation'
    | '/projects'
    | '/screw-piles'
    | '/applications/$slug'
    | '/blog/$slug'
    | '/applications'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/facility'
    | '/installation'
    | '/projects'
    | '/screw-piles'
    | '/applications/$slug'
    | '/blog/$slug'
    | '/applications/'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FacilityRoute: typeof FacilityRoute
  InstallationRoute: typeof InstallationRoute
  ProjectsRoute: typeof ProjectsRoute
  ScrewPilesRoute: typeof ScrewPilesRoute
  ApplicationsSlugRoute: typeof ApplicationsSlugRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ApplicationsIndexRoute: typeof ApplicationsIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facility': {
      id: '/facility'
      path: '/facility'
      fullPath: '/facility'
      preLoaderRoute: typeof FacilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installation': {
      id: '/installation'
      path: '/installation'
      fullPath: '/installation'
      preLoaderRoute: typeof InstallationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screw-piles': {
      id: '/screw-piles'
      path: '/screw-piles'
      fullPath: '/screw-piles'
      preLoaderRoute: typeof ScrewPilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/': {
      id: '/applications/'
      path: '/applications'
      fullPath: '/applications/'
      preLoaderRoute: typeof ApplicationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/$slug': {
      id: '/applications/$slug'
      path: '/applications/$slug'
      fullPath: '/applications/$slug'
      preLoaderRoute: typeof ApplicationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FacilityRoute: FacilityRoute,
  InstallationRoute: InstallationRoute,
  ProjectsRoute: ProjectsRoute,
  ScrewPilesRoute: ScrewPilesRoute,
  ApplicationsSlugRoute: ApplicationsSlugRoute,
  BlogSlugRoute: BlogSlugRoute,
  ApplicationsIndexRoute: ApplicationsIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
