// src/lib/checkout.ts
// src/lib/checkout.ts
import { api } from "@/lib/api";

export type CheckoutForm = {
  name: string; email: string; phone: string;
  company?: string; gstin?: string;
  address: string; city: string; state: string; pincode: string; notes?: string;
};

export type PaymentState =
  | "PENDING" | "PAYMENT_SUBMITTED" | "CONFIRMED" | "DISPATCHED" | "REJECTED" | "EXPIRED";

export type PaymentInfo = {
  state: PaymentState;
  // only present while state === "PENDING"
  upi_link?: string;
  qr?: string;            // data:image/png;base64,... generated by YOUR server
  amount_paise?: number;
  expires_at?: string;
};

export type OrderItemInput = { slug: string; quantity: number };

// The order's secret token lives only in this browser tab (never in the URL).
const tokenKey = (orderId: string) => `bs_order_${orderId}`;
export const getOrderToken = (orderId: string) => sessionStorage.getItem(tokenKey(orderId)) || "";

/**
 * Call from your cart / checkout page:
 *
 *   const orderId = await createOrder(form, [{ slug: "your-product-slug", quantity: 50 }]);
 *   navigate({ to: "/payment", search: { order: orderId } });
 *
 * Prices are NOT sent – the server calculates them.
 */
export async function createOrder(
  form: CheckoutForm,
  items: OrderItemInput[],
): Promise<string> {
  const o = await api("/orders/", { method: "POST", body: JSON.stringify({ ...form, items }) });
  sessionStorage.setItem(tokenKey(o.order_id), o.public_token);
  return o.order_id;
}

export const fetchPayment = (orderId: string): Promise<PaymentInfo> =>
  api("/orders/status/", {
    method: "POST",
    body: JSON.stringify({ order_id: orderId, public_token: getOrderToken(orderId) }),
  });

export const submitUtr = (orderId: string, utr: string) =>
  api("/orders/pay/", {
    method: "POST",
    body: JSON.stringify({ order_id: orderId, public_token: getOrderToken(orderId), utr }),
  });